# This workflow will setup Swift
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Setup

on: workflow_dispatch

jobs:
  setup-swift:
    name: Setup Swift
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        swift-version: ['6.2', '6.1']
        soft-fail-version-check: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Swift (via sonderformat-llc)
        uses: sonderformat-llc/setup-swift@main
        with:
          swift-version: ${{ matrix.swift-version }}
          soft-fail-version-check: ${{ matrix.soft-fail-version-check }}
